<div class="modal-body">
<p><strong>Preliminar</strong></p>
<p><span>Dr-Teach les da la bienvenida, Dr-Teach de ahora en adelante ser&aacute; denominado como: &quot;El Servicio&quot; o el &quot;Website&quot;. En respeto a su privacidad le haremos saber qu&eacute; informaci&oacute;n brindada utilizamos y que es lo que hacemos con dicha informaci&oacute;n. La siguiente Pol&iacute;tica de Privacidad fue creada para ayudarlo a entender c&oacute;mo ser&aacute; usada la informaci&oacute;n que usted provee a Dr-Teach. Esta Pol&iacute;tica de Privacidad aplica para toda la informaci&oacute;n que recolectamos sobre usted. </span></p>
<p><span>Informaci&oacute;n que recolectamos</span></p>
<p><strong>Informaci&oacute;n de Registro.</strong><span> No se requiere que usted nos d&eacute; a nosotros ning&uacute;n tipo de informaci&oacute;n personal para acceder a nuestro Website ni para ver la informaci&oacute;n que proveemos generalmente en nuestro Website. Sin embargo, podremos ofrecerle la oportunidad de registrarse con nosotros o unirse a nuestra lista de correo. A pesar de que no es necesario registrarse para acceder a nuestra Website, s&iacute; es necesario conectar cuentas de redes sociales para participar en los chats. En caso de querer participar en un curso necesitaremos sus datos personales para el registro en cada curso as&iacute; como ser redireccionado a alg&uacute;n medio de pago (Paypal, entre otros) para realizar el pago respectivo. En otros momentos, puede que tambi&eacute;n se le pida que nos provea informaci&oacute;n adicional, como su edad, g&eacute;nero, y otra informaci&oacute;n personal para que usted reciba informaci&oacute;n adicional de nuestros servicios a futuro.</span></p>
<p style="margin-left:36pt"><span>Dr-Teach podr&iacute;a necesitar esta informaci&oacute;n para conocerlo mejor, ayudarlo a entender nuevos servicios, programas y ofertas en las cuales usted pueda estar interesado y as&iacute; mejorar su experiencia online.</span></p>
<p><strong>Recolecci&oacute;n Autom&aacute;tica de Datos</strong><span>. Usted podr&aacute; visitar nuestra Website y usar ciertos de nuestros servicios de manera an&oacute;nima. No obstante, aunque se haya registrado con nosotros o no, Dr-Teach puede recolectar cierta informaci&oacute;n personal para el uso de nuestros servicios. Por ejemplo, Dr-Teach puede recolectar informaci&oacute;n concerniente al tipo de Navegador de Internet que usted usa, el tipo de computadora o sistema operativo que usted usa, su direcci&oacute;n de IP, la velocidad de su conexi&oacute;n, el nombre del dominio de su proveedor de servicio Internet, la localidad geogr&aacute;fica de d&oacute;nde usted est&aacute; accediendo a nuestros servicios y/o la Website o propaganda de donde usted se conect&oacute; a nuestro Website. Una vez que se haya registrado con nosotros, tambi&eacute;n rastreamos y recolectamos informaci&oacute;n sobre usted incluyendo sus transacciones con nosotros y los patrones que sigui&oacute; usted al usar nuestra Website, como las p&aacute;ginas de la Website que usted visit&oacute;, b&uacute;squedas que condujo, y el tiempo que usted estuvo en nuestra Website. Si decide contactarnos, podremos guardar un historial de su correspondencia.</span></p>
<p><strong>Cookies.</strong><span> Cuando usted visita nuestra Website o pulsa cualquier hiperv&iacute;nculo que aparece en ella, o usa uno o m&aacute;s de nuestros servicios, podremos usar una tecnolog&iacute;a industrial llamada &quot;cookies&quot; la cual almacena cierta informaci&oacute;n en su computadora y que nos permitir&aacute; personalizar su experiencia para alinearla con sus intereses y preferencias o simplemente facilitar su acceso al usar nuestros servicios. La mayor&iacute;a de los Navegadores permitir&aacute;n que usted elimine o bloquee las &quot;cookies&quot; de su computador o su disco duro o alertar&aacute; las mismas cuando estas se activen. Por favor refi&eacute;rase a las instrucciones de su Navegador para ayuda o para conocer mejor sus funciones. Por favor note, sin embargo, que si usted bloquea de su Navegador el uso de estos cookies, el servicio no podr&aacute; ser utilizado o no podr&aacute; acceder a nuestra Website o quiz&aacute;s pueda afectar el funcionamiento de la p&aacute;gina como tal.</span></p>
<p>&nbsp;</p>
<p><span>Lo que hacemos con su informaci&oacute;n</span></p>
<p><span>En general, Dr-Teach podr&aacute; usar su informaci&oacute;n para proporcionar y mejorar El Servicio. Dr-Teach podr&aacute; compartir esta informaci&oacute;n con los proveedores del servicio sobre contenido y otras entidades de forma no-personal para estudios demogr&aacute;ficos e informaci&oacute;n preferencial para los usuarios del servicio o para otros prop&oacute;sitos. Esta informaci&oacute;n podr&aacute; incluir el uso y la data demogr&aacute;fica, pero no incluir&aacute; informaci&oacute;n personal (tal como su direcci&oacute;n de correo electr&oacute;nico).</span></p>
<p><span>Dr-Teach no revelar&aacute;, compartir&aacute;, vender&aacute; ni rentar&aacute; informaci&oacute;n personal recolectada en nuestra Website a terceros para su uso promocional sin su consentimiento a menos que sea para un programa espec&iacute;fico al que le podr&aacute; pedirnos no participar. Cualquier uso de esa informaci&oacute;n de parte de Dr-Teach &nbsp;estar&aacute; sujeto a esta Pol&iacute;tica de Privacidad. Nosotros no compartimos la informaci&oacute;n de sus cuentas de tarjetas de cr&eacute;dito con redes afiliadas ni ning&uacute;n otro tercero, excepto al servicio de procesamiento de tarjetas de cr&eacute;dito descritos abajo.</span></p>
<p><span>Para mantenerlo informado sobre nuestros servicios, podr&iacute;amos enviar correos electr&oacute;nicos y anuncios que son necesarios para la administraci&oacute;n de nuestro Website y El Servicio. Tambi&eacute;n podr&iacute;amos proveer a nuestros usuarios con la opci&oacute;n de unirse a nuestra lista de correos electr&oacute;nicos para recibir informaci&oacute;n adicional sobre nuestra Website, servicios y ofertas.</span></p>
<p><span>Seguridad</span></p>
<p><span>Usamos m&eacute;todos razonables de seguridad para proteger la data que reside en nuestros servidores. Sin embargo, ning&uacute;n sistema de seguridad es impenetrable, debido a esto, no le podemos garantizar la seguridad de nuestros servidores. Es tambi&eacute;n posible que la informaci&oacute;n que usted nos provea pueda ser interceptada durante la transmisi&oacute;n de datos.</span></p>
<p><span>Cada vez que usted le brinde a Dr-Teach informaci&oacute;n sensible (ejemplo: contrase&ntilde;as, n&uacute;meros de tarjeta de cr&eacute;dito, etc), Dr-Teach tomara medidas comerciales razonables para proteger dicha informaci&oacute;n y establecer una conexi&oacute;n segura con nuestro Navegador de Web. Dr-Teach emplea una tecnolog&iacute;a industrial est&aacute;ndar conocida como secure-socket-layer (&quot;SSL&quot;) para proteger la transmisi&oacute;n de informaci&oacute;n de pago al Website. Puede usted chequear la seguridad de su conexi&oacute;n tras observar la barra de direcciones en su ventana de Navegador. Cuando usted acceda un servidor protegido por SSL, los primeros caracteres de la direcci&oacute;n cambiaran de &quot;http&quot; a &quot;https.&quot;</span></p>
<p><span>La Pol&iacute;tica de Privacidad de Dr-Teach no se extiende a nada inherente en la operaci&oacute;n de Internet, por lo tanto m&aacute;s lejos del control de Dr-Teach y no se aplicar&aacute; de ninguna manera contraria a la ley o los reglamentos del gobierno.</span></p>
<p><span>Protecci&oacute;n al menor</span></p>
<p><span>En cumplimiento del Acta Federal de 1998 para la Privacidad On-line y la Protecci&oacute;n de Ni&ntilde;os (COPPA), no pediremos conscientemente informaci&oacute;n personal de ninguna persona menor a trece (13) a&ntilde;os sin el consentimiento de sus padres. Cualquier persona que nos proporciona este tipo de informaci&oacute;n representa que tiene 13 o m&aacute;s a&ntilde;os de edad.</span></p>
<p><span>Enlaces a otras redes</span></p>
<p><span>Los enlaces a otras redes son una parte integral de la funcionalidad de Internet, incluyendo nuestra WebSite. Cualquier hiperv&iacute;nculo que disponga de una URL de un dominio distinto a Dr-Teach en la barra de direcciones de su Navegador es un hiperv&iacute;nculo a una p&aacute;gina fuera de nuestro servicio. Estas otras redes podr&aacute;n enviar sus &quot;cookies&quot; a usted, recolectar data o solicitar informaci&oacute;n personal. Dr-Teach no puede garantizar y no se hace responsable por el contenido de otras redes o p&aacute;ginas.</span></p>
<p><span>Dr-Teach no garantizar&aacute; la seguridad ni la privacidad de ninguna informaci&oacute;n que usted revele a otros Websites, y usted lo hace a su propio riesgo. Debe aprender sobre las pr&aacute;cticas y pol&iacute;ticas de privacidad y seguridad de sitios de Internet externos antes de proporcionarles sus datos personales.</span></p>
<p><span>Como examinar, actualizar o borrar la informaci&oacute;n de registro</span></p>
<p><span>Como parte del uso de nuestros servicios, usted es responsable de actualizar la informaci&oacute;n sometida para que sea actualizada y completa. Para actualizar su informaci&oacute;n de registro, por favor acceda a su cuenta de Dr-Teach y haga el cambio deseado en modificar perfil. Usted tambi&eacute;n podr&aacute; acceder su cuenta de Dr-Teach para cambiar sus preferencias tales como cancelar su suscripci&oacute;n a la lista de correos electr&oacute;nicos.</span></p>
</div>